# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - o247-shared-api-dev01

on:
  push:
    branches:
      - nonprod
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.13' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create, start virtual environment and install dependencies
        run: |
          INCLUDE="functions/ function_app.py host.json requirements.txt local.settings.json"
          echo "Machine info: $(uname --all)"
          echo "Listing the available Python exec paths..."
          ls -la /usr/bin/python*
          echo "Used Python version: $(python --version) ($(which python))"
          echo "Current working directory: $(pwd)"
          # Install Python Dependencies
          echo "Upgrading pip package installer..."
          python -m pip install --upgrade pip
          echo "Installing dependecies..."
          mkdir -p ${{ env.PACKAGE_CODE_DIR }}
          rm -r ${{ env.PACKAGE_CODE_DIR }}
          python -m pip install -r requirements.txt --target=${{ env.PACKAGE_CODE_DIR }} --no-cache-dir --force-reinstall --upgrade
          # Move package release artifacts to package_code directory
          echo "Copying Package Release Artifacts to ${{ env.PACKAGE_CODE_DIR }} directory..."
          cp -R $INCLUDE --target-directory=${{ env.PACKAGE_CODE_DIR }}
          echo "Azure Function deployment directory created. ${{ env.PACKAGE_CODE_DIR }} contains:"
          ls ${{ env.PACKAGE_CODE_DIR }}
          echo "Build completed successfully."
      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.PACKAGE_CODE_DIR }}
          zip -r ../release.zip ./*
          cd ..


      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip
        
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'o247-shared-api-dev01'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7AE1C8C24A864C56AB0711BF0CCD7ADB }}
          sku: 'flexconsumption'
        
